name: frigo_app
description: "Gérer le frigo, dates de péremption, calendrier, recettes (squelette)."
publish_to: 'none'
version: 0.1.0



environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  intl: ^0.19.0
  table_calendar: ^3.1.2

  # UI
  google_fonts: ^6.2.1

  # Routing
  go_router: ^14.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  generate: true